---
apiVersion: v1
kind: ImageStream
metadata:
  name: elixir
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations:
        description: "Build and run Elixir application"
        tags: builder,elixir
        sampleRepo: https://github.com/es1o/s2i-elixir.git
      from:
        kind: DockerImage
        name: 'es1o/s2i-elixir:1.4'
      importPolicy: {}
      name: '1.5'
      referencePolicy:
        type: Source
